Minecard
ICP-hub/StarDustAdventures pull request #20
Opened 2024-11-12 12:00 UTC by harsh-quadB

## Description
Please include a summary of the changes and the purpose of this PR.

- What does this PR do?
- Why is it needed?

## Screenshots
Include screenshots for **both desktop and mobile** versions.

### Desktop:
[Add screenshot here]

### Mobile:
[Add screenshot here]

## Approach
Briefly explain the approach taken to implement the changes. 

- How did you solve the problem?
- Any particular design patterns or optimizations?

## Issue Number (if any)
Link to the issue this PR addresses, if applicable:

Fixes #[issue_number]

## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have checked my code and corrected any misspellings

2024-11-12 12:32 UTC, BeginArjun requested changes
Kindly first pull Changes from the PR #19 after it gets approved and after then start working on these changes.

2024-11-12 12:32 UTC, BeginArjun commented on src/game_frontend/src/components/ui/Minecard/index.tsx
> +interface CardDataType {
All interfaces should be stored inside `types/[Component]/index.d.ts`

2024-11-12 12:32 UTC, BeginArjun commented on src/game_frontend/src/components/ui/Minecard/index.tsx
> +const MineCardsPage: React.FC = () => {
No need for this component. Pls remove it

2024-11-12 12:32 UTC, BeginArjun commented on src/game_frontend/src/components/ui/Minecard/index.tsx
> +const Card: React.FC<CardProps> = ({
This should be the default export

2024-11-12 12:32 UTC, BeginArjun commented on src/game_frontend/src/components/ui/Minecard/index.tsx
> +const cardData: CardDataType[] = [
Static data shouldn't be in this file. Kindly remove it or comment it

2024-11-12 12:32 UTC, BeginArjun commented on src/game_frontend/src/components/ui/Minecard/index.tsx
> +interface TabsProps {
Not specific to this component

2024-11-12 12:32 UTC, BeginArjun commented on src/game_frontend/src/components/ui/Minecard/index.tsx
> +              src={image || 'https://cdn.pixabay.com/photo/2023/06/13/15/05/astronaut-8061095_640.png'}
Why is a default image being used? This shouldn't be here.

2024-11-12 12:32 UTC, BeginArjun commented on src/game_frontend/src/components/ui/Minecard/index.tsx
> +              <span className="mine-card-icon">ic</span>
Where is `ic` written in Figma?

2024-11-12 12:32 UTC, BeginArjun commented on src/game_frontend/src/components/ui/Minecard/index.tsx
> +            <span className="mine-card-level">Lvl {level}</span>
It should be
```jsx
<span className="mine-card-level">Lvl. {level}</span>
```

2024-11-12 12:32 UTC, BeginArjun commented on src/game_frontend/src/components/ui/Minecard/index.tsx
> +  level,
default level should be 0

2024-11-13 10:08 UTC, ArjunQBTech approved these changes
Great Work!

2024-11-13 10:56 UTC, merged