Add: Info Button Tooltip
ICP-hub/StarDustAdventures pull request #54
Opened 2024-12-05 10:43 UTC by shadabkhan16

## Description
Add an info button in the airdrop's incentive component. 

- What does this PR do?
- Why is it needed?

## Screenshots
<img width="1435" alt="Screenshot 2024-12-05 at 4 01 04 PM" src="https://github.com/user-attachments/assets/2e266f38-fd08-4348-b578-be102e689266">

### Desktop:
[Add screenshot here]

### Mobile:
[Add screenshot here]

## Approach
Add div tags  flex

- How did you solve the problem?
- Any particular design patterns or optimizations?

## Issue Number (if any)
Link to the issue this PR addresses, if applicable:

Fixes #[issue_number]

## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have checked my code and corrected any misspellings

2024-12-05 14:26 UTC, ArjunQBTech requested changes

2024-12-05 14:26 UTC, ArjunQBTech commented on src/game_frontend/src/components/dashboard/airdrop/Incentives/index.tsx
> +                <img src="/assets/images/Info.svg" alt="" />
Add alt attribute as well as `loading='lazy'` attribute

2024-12-05 14:26 UTC, ArjunQBTech commented on src/game_frontend/src/components/dashboard/airdrop/Incentives/index.tsx
> +            <div className='incentive-info-svg'>
Separate this into a different component
Example : 
```jsx
<InfoToolTip/>
```

2024-12-06 06:13 UTC, shadabkhan16 commented on src/game_frontend/src/components/dashboard/airdrop/Incentives/index.tsx
> +                <img src="/assets/images/Info.svg" alt="" />
<img width="1423" alt="Screenshot 2024-12-06 at 10 11 01 AM" src="https://github.com/user-attachments/assets/5c1fc038-3147-4c3e-8a8d-0e39a9f6662f">
All necessary changes have been made.

2024-12-06 06:41 UTC, ArjunQBTech requested changes

2024-12-06 06:41 UTC, ArjunQBTech commented on src/game_frontend/src/components/dashboard/airdrop/Incentives/index.tsx
> +                <InfoTooltip title={type}> <img src="/assets/images/Info.svg" alt="info" loading='lazy' width={20} height={20} /> </InfoTooltip>
Add the children to next line

2024-12-06 06:41 UTC, ArjunQBTech commented on src/game_frontend/src/components/ui/Tooltip/index.tsx
> +interface InfoTooltipProps {
Rename to Tooltip

2024-12-06 06:41 UTC, ArjunQBTech commented on src/game_frontend/src/components/ui/Tooltip/index.tsx
> +const InfoTooltip: React.FC<InfoTooltipProps> = ({ title, children }) => {
Rename to Tooltip

2024-12-06 11:08 UTC, ArjunQBTech requested changes

2024-12-06 11:08 UTC, ArjunQBTech commented on src/game_frontend/src/components/dashboard/airdrop/Incentives/index.tsx
> +                <Tooltip title={type}>
Create a separate component : 
```tsx
const InfoToolTip=()=>{
       return (
        <Tooltip title={type}>
                     <img src="/assets/images/Info.svg" alt="info" loading='lazy' width={20} height={20} />
                </Tooltip>
       )
}
```

2024-12-07 05:12 UTC, shadabkhan16 commented on src/game_frontend/src/components/dashboard/airdrop/Incentives/index.tsx
> +                <Tooltip title={type}>
separate component for InfoToolTip

2024-12-07 06:51 UTC, ArjunQBTech approved these changes
Great 👍

2024-12-09 06:09 UTC, merged