Improve buttons  layout
ICP-hub/StarDustAdventures pull request #60
Opened 2024-12-07 09:16 UTC by shadabkhan16

## Description
Please include a summary of the changes and the purpose of this PR.

- What does this PR do?
- Why is it needed?

## Screenshots
<img width="1434" alt="Screenshot 2024-12-07 at 12 45 43 PM" src="https://github.com/user-attachments/assets/c75edcf7-5667-45ab-a9a9-14285321c23f">

### Desktop:
[Add screenshot here]

### Mobile:
[Add screenshot here]

## Approach
Briefly explain the approach taken to implement the changes. 

- How did you solve the problem?
- Any particular design patterns or optimizations?

## Issue Number (if any)
Link to the issue this PR addresses, if applicable:

Fixes #[issue_number]

## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have checked my code and corrected any misspellings

2024-12-09 06:14 UTC, ArjunQBTech requested changes

2024-12-09 06:14 UTC, ArjunQBTech commented on src/game_frontend/src/pages/Dashboard/InviteFriends/index.tsx
> +          <Button className="text-sm md:text-2xl lg:text-4xl">
Don't use tailwind css directly

2024-12-09 06:14 UTC, ArjunQBTech commented on src/game_frontend/src/pages/Dashboard/InviteFriends/index.tsx
> +          <Button className="invite-button text-sm md:text-2xl lg:text-4xl ">
Don't use Tailwind css directly

2024-12-09 06:14 UTC, ArjunQBTech commented on src/game_frontend/src/pages/Dashboard/InviteFriends/index.tsx
> +          <Button  size={'xs'}>
Button does not accepts `size='xs'`

2024-12-09 12:45 UTC, shadabkhan16 commented
<img width="1435" alt="Screenshot 2024-12-09 at 6 12 09 PM" src="https://github.com/user-attachments/assets/817c804f-6402-4936-8e54-b8d163ecfa29">

2024-12-11 06:03 UTC, ArjunQBTech approved these changes

2024-12-11 06:03 UTC, merged